# Generated by Django 5.2.1 on 2025-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_car_model_user_has_ac_alter_ride_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
