# Generated by Django 5.2.1 on 2025-05-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='seats_available',
        ),
        migrations.AddField(
            model_name='ride',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='seats',
            field=models.PositiveIntegerField(default='0000000000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
