# Generated by Django 5.2.1 on 2025-05-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ride_driver_alter_ride_price_alter_ride_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.ride'),
        ),
    ]
