# Generated by Django 5.2.1 on 2025-05-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_female',
            field=models.BooleanField(default=False),
        ),
    ]
