# Generated by Django 5.2.1 on 2025-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_hide_phone_user_is_female'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
    ]
