# Generated by Django 5.2.1 on 2025-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_female',
        ),
        migrations.AddField(
            model_name='ride',
            name='has_female_passenger',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, null=True),
        ),
    ]
